source ~/.term_profile

export EDITOR=vim

source @fzf_src@/shell/key-bindings.bash
export FZF_TMUX=0

export ERL_AFLAGS="-kernel shell_history enabled"

export GOPATH="/home/kamil"
export PATH="$GOPATH/bin:/home/kamil/.nix-profile/bin:$PATH"

export JAVA_HOME="@jdk@"
